[build-system]
# These are the assumed default build requirements from pip:
requires = [
    "setuptools>=80.9", 
    "wheel", 
    "pybind11>=3.0",
    "maturin"
]
build-backend = "setuptools.build_meta"